version: '3'
services:
   nginx-proxy:
     build: ./nginx
     image: 'sonatype-se/sonatype_nginx-proxy:2.6.3'
     ports:
       - '443:443'
       - '5000:5000'
       - '8011:8011'
     command:
       - nginx
       - '-g'
       - daemon off;
     depends_on:
       - iq-server
       - nexus

   nexus:
     image: 'sonatype/nexus3:3.22.0'
     volumes:
       - '~/.demo-pv/nexus-data:/nexus-data:delegated'
     ports:
       - '8081:8081'
       - '18443:18443'

   iq-server:
     image: 'sonatype-se/my-iq-server:1.88.0'
     build: ./iq-server
     volumes:
       - '~/.demo-pv/iq-data:/sonatype-work:delegated'
       - '~/.demo-pv/iq-logs:/opt/sonatype/nexus-iq-server/log:delegated'
     ports:
       - '8070:8070' 
       - '8071:8071'
       