version: '3.9'

x-env-license: &env-license-volume
  '${NEXUS_LICENSE_PATH:?err}:/sonatype-license.lic'

x-nxrm3-volume-nexus-properties: &nxrm3-volume-nexus-properties
  './config/nexus-repo.properties:/nexus-data/etc/nexus.properties'

x-nxrm3-volume-casc-config: &nxrm3-volume-casc-config
  './config/nexus-repos-casc.yaml:/opt/nexus.yml:ro'

x-nxrm3-volume-data: &nxrm3-volume-data
  '${DOCKER_ROOT_VOLUME_MOUNT_POINT:?err}/nexus-data:/nexus-data:delegated'

secrets:
  admin_password:
    file: ./config/admin_password

services:

  nxiq_direct:
    image: "sonatype/nexus-iq-server:${NEXUS_IQ_SERVER_VERSION:?err}"
    environment:
      BASE_URL: "http://iq.localhost:8070"
    healthcheck:
      # Disabled as if no valid license, healthcheck fails
      disable: true
    ports:
      - "8070:8070"
      - "8071:8071"
    profiles:
      - direct
    secrets:
      - admin_password
    volumes:
      - *env-license-volume
      - "./config/nexus-iq-config.yaml:/etc/nexus-iq-server/config.yml:delegated"
      - "${DOCKER_ROOT_VOLUME_MOUNT_POINT:?err}/iq-data:/sonatype-work:delegated"
      - "${DOCKER_ROOT_VOLUME_MOUNT_POINT:?err}/iq-logs:/opt/sonatype/nexus-iq-server/log:delegated"

  nxiq_proxied:
    image: "sonatype/nexus-iq-server:${NEXUS_IQ_SERVER_VERSION:?err}"
    environment:
      BASE_URL: "http://iq.localhost"
    healthcheck:
      # Disabled as if no valid license, healthcheck fails
      disable: true
    ports:
      - "8070:8070"
      - "8071:8071"
    profiles:
      - proxied
    secrets:
      - admin_password
    volumes:
      - *env-license-volume
      - "./config/nexus-iq-config.yaml:/etc/nexus-iq-server/config.yml:delegated"
      - "${DOCKER_ROOT_VOLUME_MOUNT_POINT:?err}/iq-data:/sonatype-work:delegated"
      - "${DOCKER_ROOT_VOLUME_MOUNT_POINT:?err}/iq-logs:/opt/sonatype/nexus-iq-server/log:delegated"
    
  nxrm3_direct:
    build: ./nxrm3
    environment:
      BASE_URL: 'http://repo.localhost:8081'
      NEXUS_SECURITY_RANDOMPASSWORD: 'false'
      NEXUS_CASC_CONFIG: '/opt/nexus.yml'
      NEXUS_IQ_BASE_URL: 'http://iq.localhost:8070'
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    ports:
      - '8081:8081'
    profiles:
      - direct
    secrets:
      - admin_password
    volumes: 
      - *env-license-volume
      - *nxrm3-volume-nexus-properties
      - *nxrm3-volume-casc-config
      - *nxrm3-volume-data

  nxrm3_proxied:
    build: ./nxrm3
    environment:
      BASE_URL: 'http://repo.localhost'
      NEXUS_SECURITY_RANDOMPASSWORD: 'false'
      NEXUS_CASC_CONFIG: '/opt/nexus.yml'
      NEXUS_IQ_BASE_URL: 'http://iq.localhost:8070'
    profiles:
      - proxied
    ports:
      - '8081:8081'
    secrets:
      - admin_password
    volumes: 
      - *env-license-volume
      - *nxrm3-volume-nexus-properties
      - *nxrm3-volume-casc-config
      - *nxrm3-volume-data

  proxy:
    image: "nginx:${NGINX_VERSION:?err}"
    depends_on: 
      - nxrm3_proxied
      - nxiq_proxied
    environment:
      - NGINX_HOST=nexus-platform.localhost
      - NGINX_PORT=80
    ports:
      - "80:80"
    profiles:
      - proxied
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./config/nginx-www:/usr/share/nginx/html:ro"
    