version: "3.7"

services:
  nginx-proxy:
    image: "nginx:${NGINX_VERSION:?err}"
    environment:
      - NGINX_HOST=nexus-platform.localhost
      - NGINX_PORT=80
    secrets:
      - admin_password
    volumes:
      - "../config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../config/nginx-www:/usr/share/nginx/html:ro"
    ports:
      - "80:80"
